config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get 'pages/about'

  root 'project#index'

  resources :project do
    resources :task, only: [:show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks

  validates :name, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 500 }
  validates :price, presence: true, numericality: { only_integer: true }

  has_attached_file :image, styles: { medium: "680x300>", thumb: "175x70>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :title, presence: true, length: { maximum: 50 }
  validates :video, presence: true
  validates :tag, presence: true
  validates :project, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  validates :name, presence: true, length: {maximum: 25}

def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
  data = access_token.info
  user = User.where(:provider => access_token.provider, :uid => access_token.uid).first

  if user
    return user
  else
    registered_user = User.where(:email => access_token.email).first
    if registered_user
      return registered_user
    else
      user = User.create(
        name: data["name"],
        provider: access_token.provider,
        email: data["email"],
        uid: access_token.uid,
        image: data["image"],
        password: Devise.friendly_token[0, 20]
      )
    end
  end
end

def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
  data = access_token.info
  user = User.where(:provider => access_token.provider, :uid => access_token.uid).first

  if user
    return user
  else
    registered_user = User.where(:email => data.email).first
    if registered_user
      return registered_user
    else
      user = User.create(
        name: access_token.extra.raw_info.name,
        provider: access_token.provider,
        email: data.email,
        uid: access_token.uid,
        image: data.image,
        password: Devise.friendly_token[0, 20]
      )
    end
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :remember_me) }
  	devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :email, :password, :remember_me) }
  	devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def show
    project = Project.find(params[:project_id])
    @tasks = project.tasks
    @task = @tasks.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase
		if user.image
			user.image
		else
			"https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identicon&s=40"
		end
	end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code4Pro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>

  <%= render partial: "shared/header" %>
  <%= render partial: "shared/message" %>

  <main>
    <div class="container">
      <%= yield %>
    </div>
  </main>

  <%= render partial: "shared/footer" %>

  </body>

  <script>
    $(".button-collapse").sideNav();
    $(".dropdown-button").dropdown();
  </script>

</html>

app/views/pages/about.html.erb
<h3>About Me</h3>

<div class="card z-depth-3">
  <div class="card-content white-text">
  	<div class="row">
	    <div class="col m6">
	      <a class="twitter-timeline" href="https://twitter.com/Code4Startup" data-widget-id="584941191998877696">Tweets by @Code4Startup</a>

	      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	    </div>
	    <div class="col m6">
	      <div class="card-panel grey lighten-5 z-depth-1">
	          <div class="row valign-wrapper">
	            <div class="col s3">
	              <%= image_tag "avatar.jpg", class: "circle responsive-img" %>
	            </div>
	            <div class="col s9">
	              <span class="black-text">
	                I don't know what to say. Let the world tell you more... :)
	              </span>
	            </div>
	          </div>
	        </div>
	    </div>
    </div>
  </div>
</div>

app/views/project/index.html.erb
<div class="row">
</br>

<% @projects.each do |project| %>

  <%= link_to project do %>
      <div class="col s12 m6">
        <div class="card">
          <div class="card-image waves-effect waves-block waves-light">
            <%= image_tag project.image %>
          </div>

        <div class="card-content">
          <span class="card-title grey-text text-darken-4">
            <%= project.name %>
          </span>
        </div>

      </div>
    </div>
  <% end %>

<% end %>

</div>

app/views/project/show.html.erb
<div class="row">
	<div class="col m4">
		<div class="card z-depth-2">
			<div class="center">
				<h1>$<%= @project.price %></h1>
			</div>
			<div class="card-action center">
				<button class="btn waves-effect waves-light pink darken-2">
					Take this Project
				</button>
			</div>
		</div>
	</div>

	<div class="col m8">
		<div class="card z-depth-2">
			<div class="card-image">
				<%= image_tag @project.image %>
			</div>
			<div class="card-content grey-text text-darken-4">
				<h5><%= @project.name %></h5>
				<hr>
				<%= @project.content %>

				<div class="collection">
					<% @tasks.each do |task| %>
						<% if task.header %>
							<div class="collection-item active">
								<i class="mdi-social-school"> <%= task.title %></i>
							</div>
						<% else %>
							<%= link_to [task.project, task], class: "collection-item" do %>
								<%= task.title %>
							<% end %>
						<% end %>
					<% end %>
				</div>

			</div>
		</div>
	</div>

</div>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
	<% resource.errors.full_messages.each do |msg| %>
		toastr.error('<%= msg %>')
	<% end %>
	</script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer brown lighten-4">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Code4Pro</h5>
        <p class="grey-text text-lighten-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Social</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Google Plus</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">LinkedIn</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2016 Copyright Code4Pro
    <%= link_to "About Us", pages_about_path, :class => "grey-text text-lighten-4 right" %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>

  <!-- Dropdown Structure -->
  <ul id="dropdown1" class="dropdown-content">
    <li><%= link_to "My Profile", edit_user_registration_path %></li>
    <li><a href="#!">My Courses</a></li>
    <li class="divider"></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>

  <ul id="dropdown2" class="dropdown-content">
    <li><%= link_to "My Profile", edit_user_registration_path %></li>
    <li><a href="#!">My Courses</a></li>
    <li class="divider"></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  </ul>

<nav class="brown lighten-4 z-depth-2">
  <div class="container">
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Code4Pro</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Courses</a></li>

        <% if(!user_signed_in?) %>
        <li><%= link_to "Sign Up", new_user_registration_path %></a></li>
        <li><%= link_to "Log In", new_user_session_path %></a></li>
        <% else %>
        <!-- Dropdown Trigger -->
        <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown1">
          <%= image_tag avatar_url(current_user), class: "circle responsive-img" %>&nbsp;
          <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
        <% end %>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="#">Courses</a></li>
        <% if(!user_signed_in?) %>
        <li><%= link_to "Sign Up", new_user_registration_path %></a></li>
        <li><%= link_to "Log In", new_user_session_path %></a></li>
        <% else %>
        <!-- Dropdown Trigger -->
        <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown2">
          <%= image_tag avatar_url(current_user), class: "circle responsive-img" %>&nbsp;
          <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
	<% flash.each do |f| %>
	<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
		toastr['<%= type %>']('<%= f[1] %>')
	<% end %>
	</script>
<% end %>

app/views/task/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.note %></p>
<p><%= @task.video %></p>